// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqrbnonutpfaruenkkem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxcmJub251dHBmYXJ1ZW5ra2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5OTU5MDYsImV4cCI6MjA3MTU3MTkwNn0.G33oWPOXFSzZCjOqQXZ4SPxoKcBmauYdEtGTuM8z7uY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});